translations = {
    "ru": {
        "menu.header": "LumeCore",
        "menu.title": "Меню AutoTwoFA",
        "menu.start_process": "[1] Запустить переавторизацию",
        "menu.change_language": "[2] Сменить язык",
        "menu.configure_settings": "[3] Настроить параметры",
        "menu.exit": "[4] Выход",
        "menu.select_option": "Выберите опцию [1-4]:",
        "menu.press_enter": "Нажмите Enter для продолжения...",
        "menu.starting_process": "Запуск переавторизации...",
        "menu.process_completed": "Переавторизация завершена успешно",
        "menu.process_failed": "Некоторые сессии не были переавторизованы",
        "menu.goodbye": "До свидания!",
        "menu.language_changed": "Язык изменён на {language}",
        "menu.select_language": "Выберите язык",
        "menu.select_language_option": "Выберите опцию [0-2]:",
        "menu.back": "[0] Назад",
        "menu.proxy_error": "Ошибка: {error}. Прокси необходим для переавторизации.",
        "menu.no_json_files": "Не найдено JSON-файлов в {dir}",
        "menu.error": "Ошибка: {error}",
        "menu.running": "Процесс уже выполняется",
        "menu.config_created": "Создан файл конфигурации {file}",
        "menu.dir_created": "Создана папка {dir}",
        "menu.proxy_file_created": "Создан файл прокси {file}",
        "menu.auth_data_missing": "Не удалось загрузить данные из {file}",
        "menu.auth_data_missing_creating": "JSON-файл {file} отсутствует, создаётся новый",
        "menu.auth_data_created": "JSON-файл {file} создан",
        "menu.api_data_missing_generating": "API данные отсутствуют в {file}, генерируются новые",
        "menu.api_data_generated": "API данные сгенерированы для {file}",
        "menu.phone_missing": "Номер телефона отсутствует в {file}",
        "menu.api_data_missing": "Недостаточно данных API в {file}",
        "menu.session_missing": "Сессия для {phone} не найдена",
        "menu.using_two_fa": "Используемый пароль 2FA для {phone}: {two_fa}",
        "menu.using_proxy_old": "Используется прокси для старой сессии: {host}:{port}",
        "menu.no_proxy_old": "Прокси не используются для старой сессии {phone}",
        "menu.using_proxy_new": "Используется прокси для новой сессии: {host}:{port}",
        "menu.no_proxy_new": "Прокси не используются для новой сессии {phone}",
        "menu.session_not_authorized": "Сессия для {phone} не авторизована",
        "menu.two_fa_changed": "2FA пароль для {phone} изменён на {new_two_fa}",
        "menu.invalid_two_fa": "Неверный текущий пароль 2FA для {phone}: {two_fa}",
        "menu.two_fa_change_error": "Ошибка при смене 2FA для {phone}: {error}",
        "menu.two_fa_unexpectedly_required": "Неожиданно требуется пароль 2FA для {phone}, но он не указан",
        "menu.new_client_connection_failed": "Не удалось подключиться для новой сессии {phone}",
        "menu.code_received": "Код авторизации для {phone} получен",
        "menu.code_not_received": "Код не получен для {phone}, ожидание {seconds} секунд",
        "menu.code_not_obtained": "Не удалось получить код для {phone}. Введите код вручную",
        "menu.enter_code": "Введите код авторизации для {phone}: ",
        "menu.code_not_entered": "Код не введён для {phone}",
        "menu.new_session_authorized": "Новая сессия для {phone} авторизована",
        "menu.invalid_new_two_fa": "Неверный пароль 2FA для новой сессии {phone}: {two_fa}",
        "menu.two_fa_required": "Требуется пароль 2FA для новой сессии {phone}, но он неверный: {two_fa}",
        "menu.code_invalid_or_expired": "Код недействителен или истёк для {phone}: {error}",
        "menu.code_usage_error": "Ошибка при использовании кода для {phone}: {error}",
        "menu.new_session_auth_failed": "Не удалось авторизовать новую сессию для {phone}",
        "menu.auth_data_saved": "Данные авторизации сохранены в {file}",
        "menu.old_session_closed": "Старая сессия для {phone} закрыта",
        "menu.session_file_deleted": "Файл сессии {file} удалён",
        "menu.json_file_deleted": "JSON-файл {file} удалён",
        "menu.logout_error": "Ошибка при закрытии старой сессии для {phone}: {error}",
        "menu.flood_limit": "Ограничение Telegram API для {phone}, ожидание {seconds} секунд",
        "menu.auth_restart_error": "Ошибка авторизации для {phone}: AuthRestartError",
        "menu.retries_exhausted": "Исчерпаны попытки для {phone}",
        "menu.code_options_exhausted": "Исчерпаны способы отправки кода для {phone}",
        "menu.code_request_error": "Ошибка при запросе кода для {phone}: {error}",
        "menu.session_unregistered": "Сессия для {phone} не зарегистрирована",
        "menu.session_error": "Ошибка при обработке сессии для {phone}: {error}",
        "menu.connection_failed": "Не удалось подключиться для {phone}: {error}",
        "menu.main_error": "Произошла ошибка: {error}",
        "menu.current_max_threads": "Текущее количество потоков: {value}",
        "menu.enter_max_threads": "Введите количество потоков (мин. 1):",
        "menu.max_threads_updated": "Количество потоков обновлено: {value}",
        "menu.current_retry_delay": "Текущая задержка повтора (сек): {value}",
        "menu.enter_retry_delay": "Введите задержку повтора (сек, мин. 1):",
        "menu.retry_delay_updated": "Задержка повтора обновлена: {value}",
        "menu.current_logout_old_session": "Закрывать старую сессию: {value}",
        "menu.enter_logout_old_session": "Закрывать старую сессию? [y/n]:",
        "menu.logout_old_session_updated": "Настройка закрытия старой сессии обновлена: {value}",
        "menu.current_change_2fa": "Изменять 2FA: {value}",
        "menu.enter_change_2fa": "Изменять 2FA? [y/n]:",
        "menu.select_setting_option": "Выберите параметр для настройки [0-4]:",
        "error.proxy_empty": "Файл proxy.txt пуст или отсутствует",
        "log.config_file_missing": "Файл {file} не найден, создаётся с настройками по умолчанию",
        "log.dir_created": "Создана папка: {dir}",
        "log.proxy_file_created": "Создан файл proxy.txt с примером формата",
        "log.invalid_proxy_format": "Некорректный формат строки в proxy.txt: {line}",
        "log.proxy_file_empty": "Файл {file} пуст, прокси необходим",
        "log.auth_data_missing": "Не удалось загрузить данные из {file}",
        "log.auth_data_missing_creating": "JSON-файл {file} отсутствует, создаётся новый",
        "log.auth_data_created": "JSON-файл {file} создан",
        "log.api_data_missing_generating": "API данные отсутствуют в {file}, генерируются новые",
        "log.api_data_generated": "API данные сгенерированы для {file}",
        "log.auth_data_saved": "Данные авторизации сохранены в {file}",
        "log.phone_missing": "Номер телефона отсутствует в {file}",
        "log.api_data_missing": "Недостаточно данных API в {file}: api_id или api_hash отсутствуют",
        "log.session_missing": "Сессия для {phone} не найдена в {sessions_dir}",
        "log.using_two_fa": "Используемый пароль 2FA для {phone}: {two_fa}",
        "log.using_proxy_old": "Используется прокси для старой сессии: {host}:{port}",
        "log.no_proxy_old": "Прокси не используются для старой сессии {phone}",
        "log.using_proxy_new": "Используется прокси для новой сессии: {host}:{port}",
        "log.no_proxy_new": "Прокси не используются для новой сессии {phone}",
        "log.session_not_authorized": "Сессия для {phone} не авторизована",
        "log.two_fa_changed": "2FA пароль для {phone} изменён на {new_two_fa}",
        "log.waiting_sync": "Ожидание {seconds} секунд для синхронизации нового 2FA",
        "log.invalid_two_fa": "Неверный текущий пароль 2FA для {phone}: {two_fa}",
        "log.two_fa_change_error": "Ошибка при смене 2FA для {phone}: {error}",
        "log.two_fa_unexpectedly_required": "Неожиданно требуется пароль 2FA для {phone}",
        "log.new_client_connection_failed": "Не удалось установить соединение для нового клиента для {phone}",
        "log.code_received": "Код авторизации для {phone} получен",
        "log.code_not_received": "Код не получен для {phone}, ожидание {seconds} секунд",
        "log.code_not_obtained": "Не удалось получить код для {phone}",
        "log.code_not_entered": "Код не введён для {phone}",
        "log.new_session_authorized": "Успешная авторизация новой сессии для {phone} с 2FA",
        "log.invalid_new_two_fa": "Неверный пароль 2FA для новой сессии {phone}: {two_fa}",
        "log.two_fa_required": "Требуется пароль 2FA для новой сессии {phone}, но он неверный: {two_fa}",
        "log.code_invalid_or_expired": "Ошибка авторизации для {phone}: {error}",
        "log.code_usage_error": "Ошибка при использовании кода для {phone}: {error}",
        "log.new_session_auth_failed": "Не удалось авторизовать новую сессию для {phone}",
        "log.old_session_closed": "Старая сессия для {phone} закрыта",
        "log.session_file_deleted": "Файл сессии {file} удалён",
        "log.json_file_deleted": "JSON-файл {file} удалён",
        "log.logout_error": "Ошибка при logout старой сессии для {phone}: {error}",
        "log.flood_limit": "Ограничение Telegram API для {phone}, требуется ожидание {seconds} секунд",
        "log.auth_restart_error": "Ошибка Telegram API для {phone}: AuthRestartError",
        "log.retries_exhausted": "Исчерпаны попытки для {phone}",
        "log.code_options_exhausted": "Исчерпаны способы отправки кода для {phone}",
        "log.code_request_error": "Ошибка при запросе кода для {phone}: {error}",
        "log.session_unregistered": "Сессия для {phone} не зарегистрирована",
        "log.session_error": "Ошибка при обработке сессии для {phone}: {error}",
        "log.connection_failed": "Не удалось переподключиться для {phone}: {error}",
        "log.changing_language": "Смена языка",
        "log.language_changed": "Язык изменён на {language}",
        "log.option_selected": "Выбрана опция: {choice}",
        "log.main_error": "Произошла ошибка: {error}",
        "log.configuring_settings": "Настройка параметров",
        "log.settings_updated": "Настройки обновлены",
        "log.config_saved": "Конфигурация сохранена в {file}",
        "log.max_threads_updated": "Количество потоков обновлено: {value}",
        "log.retry_delay_updated": "Задержка повтора обновлена: {value}",
        "log.logout_old_session_updated": "Настройка закрытия старой сессии обновлена: {value}",
        "log.change_2fa_updated": "Настройка изменения 2FA обновлена: {value}"
    },
    "en": {
        "menu.header": "LumeCore",
        "menu.title": "AutoTwoFA Menu",
        "menu.start_process": "[1] Start Reauthorization",
        "menu.change_language": "[2] Change Language",
        "menu.configure_settings": "[3] Configure Settings",
        "menu.exit": "[4] Exit",
        "menu.select_option": "Select an option [1-4]:",
        "menu.press_enter": "Press Enter to continue...",
        "menu.starting_process": "Starting reauthorization...",
        "menu.process_completed": "Reauthorization completed successfully",
        "menu.process_failed": "Some sessions failed to reauthorize",
        "menu.goodbye": "Goodbye!",
        "menu.language_changed": "Language changed to {language}",
        "menu.select_language": "Select language",
        "menu.select_language_option": "Select option [0-2]:",
        "menu.back": "[0] Back",
        "menu.proxy_error": "Error: {error}. Proxy is required for reauthorization.",
        "menu.no_json_files": "No JSON files found in {dir}",
        "menu.error": "Error: {error}",
        "menu.running": "Process is already running",
        "menu.config_created": "Configuration file {file} created",
        "menu.dir_created": "Directory {dir} created",
        "menu.proxy_file_created": "Proxy file {file} created",
        "menu.auth_data_missing": "Failed to load data from {file}",
        "menu.auth_data_missing_creating": "JSON file {file} is missing, creating a new one",
        "menu.auth_data_created": "JSON file {file} created",
        "menu.api_data_missing_generating": "API data missing in {file}, generating new",
        "menu.api_data_generated": "API data generated for {file}",
        "menu.phone_missing": "Phone number missing in {file}",
        "menu.api_data_missing": "Insufficient API data in {file}",
        "menu.session_missing": "Session for {phone} not found",
        "menu.using_two_fa": "Using 2FA password for {phone}: {two_fa}",
        "menu.using_proxy_old": "Using proxy for old session: {host}:{port}",
        "menu.no_proxy_old": "No proxy used for old session {phone}",
        "menu.using_proxy_new": "Using proxy for new session: {host}:{port}",
        "menu.no_proxy_new": "No proxy used for new session {phone}",
        "menu.session_not_authorized": "Session for {phone} is not authorized",
        "menu.two_fa_changed": "2FA password for {phone} changed to {new_two_fa}",
        "menu.invalid_two_fa": "Invalid current 2FA password for {phone}: {two_fa}",
        "menu.two_fa_change_error": "Error changing 2FA for {phone}: {error}",
        "menu.two_fa_unexpectedly_required": "Unexpectedly required 2FA password for {phone}, but none provided",
        "menu.new_client_connection_failed": "Failed to connect for new session {phone}",
        "menu.code_received": "Authorization code for {phone} received",
        "menu.code_not_received": "Code not received for {phone}, waiting {seconds} seconds",
        "menu.code_not_obtained": "Failed to obtain code for {phone}. Enter code manually",
        "menu.enter_code": "Enter authorization code for {phone}: ",
        "menu.code_not_entered": "Code not entered for {phone}",
        "menu.new_session_authorized": "New session for {phone} authorized",
        "menu.invalid_new_two_fa": "Invalid 2FA password for new session {phone}: {two_fa}",
        "menu.two_fa_required": "2FA password required for new session {phone}, but it is invalid: {two_fa}",
        "menu.code_invalid_or_expired": "Code is invalid or expired for {phone}: {error}",
        "menu.code_usage_error": "Error using code for {phone}: {error}",
        "menu.new_session_auth_failed": "Failed to authorize new session for {phone}",
        "menu.auth_data_saved": "Authorization data saved to {file}",
        "menu.old_session_closed": "Old session for {phone} closed",
        "menu.session_file_deleted": "Session file {file} deleted",
        "menu.json_file_deleted": "JSON file {file} deleted",
        "menu.logout_error": "Error logging out old session for {phone}: {error}",
        "menu.flood_limit": "Telegram API limit for {phone}, wait {seconds} seconds",
        "menu.auth_restart_error": "Authorization error for {phone}: AuthRestartError",
        "menu.retries_exhausted": "Retries exhausted for {phone}",
        "menu.code_options_exhausted": "All code sending options exhausted for {phone}",
        "menu.code_request_error": "Error requesting code for {phone}: {error}",
        "menu.session_unregistered": "Session for {phone} is not registered",
        "menu.session_error": "Error processing session for {phone}: {error}",
        "menu.connection_failed": "Failed to connect for {phone}: {error}",
        "menu.main_error": "An error occurred: {error}",
        "menu.current_max_threads": "Current number of threads: {value}",
        "menu.enter_max_threads": "Enter number of threads (min. 1):",
        "menu.max_threads_updated": "Number of threads updated: {value}",
        "menu.current_retry_delay": "Current retry delay (sec): {value}",
        "menu.enter_retry_delay": "Enter retry delay (sec, min. 1):",
        "menu.retry_delay_updated": "Retry delay updated: {value}",
        "menu.current_logout_old_session": "Logout old session: {value}",
        "menu.enter_logout_old_session": "Logout old session? [y/n]:",
        "menu.logout_old_session_updated": "Logout old session setting updated: {value}",
        "menu.current_change_2fa": "Change 2FA: {value}",
        "menu.enter_change_2fa": "Change 2FA? [y/n]:",
        "menu.select_setting_option": "Select setting to configure [0-4]:",
        "error.proxy_empty": "proxy.txt file is empty or missing",
        "log.config_file_missing": "File {file} not found, creating with default settings",
        "log.dir_created": "Directory created: {dir}",
        "log.proxy_file_created": "Created proxy.txt file with example format",
        "log.invalid_proxy_format": "Invalid format in proxy.txt: {line}",
        "log.proxy_file_empty": "File {file} is empty, proxy is required",
        "log.auth_data_missing": "Failed to load data from {file}",
        "log.auth_data_missing_creating": "JSON file {file} is missing, creating a new one",
        "log.auth_data_created": "JSON file {file} created",
        "log.api_data_missing_generating": "API data missing in {file}, generating new",
        "log.api_data_generated": "API data generated for {file}",
        "log.auth_data_saved": "Authorization data saved to {file}",
        "log.phone_missing": "Phone number missing in {file}",
        "log.api_data_missing": "Insufficient data in {file}: api_id or api_hash missing",
        "log.session_missing": "Session for {phone} not found in {sessions_dir}",
        "log.using_two_fa": "Using 2FA password for {phone}: {two_fa}",
        "log.using_proxy_old": "Using proxy for old session: {host}:{port}",
        "log.no_proxy_old": "No proxy used for old session {phone}",
        "log.using_proxy_new": "Using proxy for new session: {host}:{port}",
        "log.no_proxy_new": "No proxy used for new session {phone}",
        "log.session_not_authorized": "Session for {phone} is not authorized",
        "log.two_fa_changed": "2FA password for {phone} changed to {new_two_fa}",
        "log.waiting_sync": "Waiting {seconds} seconds for 2FA synchronization",
        "log.invalid_two_fa": "Invalid current 2FA password for {phone}: {two_fa}",
        "log.two_fa_change_error": "Error changing 2FA for {phone}: {error}",
        "log.two_fa_unexpectedly_required": "Unexpectedly required 2FA password for {phone}",
        "log.new_client_connection_failed": "Failed to establish connection for new client for {phone}",
        "log.code_received": "Authorization code for {phone} received",
        "log.code_not_received": "Code not received for {phone}, waiting {seconds} seconds",
        "log.code_not_obtained": "Failed to obtain code for {phone}",
        "log.code_not_entered": "Code not entered for {phone}",
        "log.new_session_authorized": "Successful authorization of new session for {phone} with 2FA",
        "log.invalid_new_two_fa": "Invalid 2FA password for new session {phone}: {two_fa}",
        "log.two_fa_required": "2FA password required for new session {phone}, but it is invalid: {two_fa}",
        "log.code_invalid_or_expired": "Authorization error for {phone}: {error}",
        "log.code_usage_error": "Error using code for {phone}: {error}",
        "log.new_session_auth_failed": "Failed to authorize new session for {phone}",
        "log.old_session_closed": "Old session for {phone} closed",
        "log.session_file_deleted": "Session file {file} deleted",
        "log.json_file_deleted": "JSON file {file} deleted",
        "log.logout_error": "Error during logout of old session for {phone}: {error}",
        "log.flood_limit": "Telegram API limit for {phone}, requires waiting {seconds} seconds",
        "log.auth_restart_error": "Telegram API error for {phone}: AuthRestartError",
        "log.retries_exhausted": "Retries exhausted for {phone}",
        "log.code_options_exhausted": "All code sending options exhausted for {phone}",
        "log.code_request_error": "Error requesting code for {phone}: {error}",
        "log.session_unregistered": "Session for {phone} is not registered",
        "log.session_error": "Error processing session for {phone}: {error}",
        "log.connection_failed": "Failed to reconnect for {phone}: {error}",
        "log.changing_language": "Changing language",
        "log.language_changed": "Language changed to {language}",
        "log.option_selected": "Selected option: {choice}",
        "log.main_error": "An error occurred: {error}",
        "log.configuring_settings": "Configuring settings",
        "log.settings_updated": "Settings updated",
        "log.config_saved": "Configuration saved to {file}",
        "log.max_threads_updated": "Number of threads updated: {value}",
        "log.retry_delay_updated": "Retry delay updated: {value}",
        "log.logout_old_session_updated": "Logout old session setting updated: {value}",
        "log.change_2fa_updated": "Change 2FA setting updated: {value}"
    }
}

def t(key, locale, **kwargs):
    return translations.get(locale, translations["en"]).get(key, key).format(**kwargs)
